---
  url:
    description: "URL of the JIRA instance (e.g. ``https://myproject.atlassian.net``)"
    type: "string"
    secret: false
    required: true
  username:
    description: "User Name"
    type: "string"
    secret: false
    required: true
  password:
    description: "Password"
    type: "string"
    secret: true
    required: true
  poll_interval:
    description: "Polling interval - default 30s"
    type: "integer"
    secret: false
    required: false
    default: 30
  project:
    description: "Project to be used as default for actions that don't require or allow a project"
    type: "string"
    secret: false
    required: true
